"""Batch add scouted ads to library."""
import sys
sys.path.insert(0, str(__import__('pathlib').Path(__file__).parent))
from harness import save_ad

ads = [
    {
        "id": "ad_001",
        "advertiser": "Airtel Xstream Fiber",
        "platform": "YouTube",
        "format": "TVC",
        "duration_seconds": 45,
        "language": "Hindi + 8 regional languages",
        "url": "https://www.airtel.in/press-release/03-2024/airtel-xstream-fiber-transforms-home-entertainment-with-its-brand-new-campaign",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2024-03",
        "vertical": "ISP/broadband",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "360-degree campaign where characters from popular entertainment shows burst onto screen with catchy soundtrack. Multi-lingual in 9 languages. Positions Xstream Fiber as ultimate big-screen entertainment solution.",
        "why_included": "Direct ISP competitor. Multi-lingual approach relevant to Wiom. Entertainment-as-hook strategy for broadband is the dominant playbook in Indian ISP ads.",
        "tags": ["entertainment-hook", "multi-lingual", "celebrity", "broadband", "problem-solution"],
        "deconstructed": False
    },
    {
        "id": "ad_002",
        "advertiser": "Lahori Zeera",
        "platform": "YouTube",
        "format": "In-Feed Video",
        "duration_seconds": 30,
        "language": "Hindi",
        "url": "https://www.linkedin.com/posts/karts_advertising-marketing-creative-activity-7192757402830540800-pZfy",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2024-05",
        "vertical": "D2C/beverage",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "Exaggerated scenarios of people consuming the beverage while performing extreme activities like running, wrestling, swimming. Over-the-top humor with fast cuts. Named among top 10 Indian ads of 2024.",
        "why_included": "Masterclass in exaggeration-as-hook. High-energy pacing and humor that cuts through clutter. Pattern worth studying: can exaggeration work for broadband speed/reliability?",
        "tags": ["humor", "exaggeration", "fast-paced", "D2C", "high-energy"],
        "deconstructed": False
    },
    {
        "id": "ad_003",
        "advertiser": "WD-40",
        "platform": "YouTube",
        "format": "Bumper",
        "duration_seconds": 6,
        "language": "Hindi",
        "url": "https://www.linkedin.com/posts/karts_advertising-marketing-creativity-activity-7230073363967225856-KpHQ/",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2024-08",
        "vertical": "Consumer goods",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "Series of eight 6-second bumper ads, each showcasing one product use-case with a humorous punchline. Extremely tight storytelling: problem-product-payoff in 6 seconds flat.",
        "why_included": "Brilliant format efficiency. If you can tell a complete story in 6 seconds, you can nail any hook. The constraint forces creative excellence. Can Wiom do 6-second problem-solution bumpers?",
        "tags": ["6-second", "bumper", "humor", "problem-solution", "tight-edit", "series"],
        "deconstructed": False
    },
    {
        "id": "ad_004",
        "advertiser": "Zomato",
        "platform": "YouTube",
        "format": "In-Feed Video",
        "duration_seconds": 60,
        "language": "Hinglish",
        "url": "https://www.linkedin.com/posts/karts_advertising-marketing-diwali-activity-7255159973616226305-ejko/",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2024-10",
        "vertical": "Consumer internet/food delivery",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "Diwali 2024 ad parodies a popular Diwali meme with satirical tone. Features actor Piyush Mishra. Cultural moment-jacking done right. Named among top 10 Indian ads of 2024.",
        "why_included": "Consumer internet brand with massive ad spend. Cultural moment-jacking plus celebrity plus satire combo. Zomato consistently produces organically shared ads worth studying.",
        "tags": ["cultural-moment", "celebrity", "satire", "hinglish", "shareability", "consumer-internet"],
        "deconstructed": False
    },
    {
        "id": "ad_005",
        "advertiser": "Urban Company",
        "platform": "YouTube",
        "format": "In-Feed Video",
        "duration_seconds": 45,
        "language": "Hindi",
        "url": "https://beastoftraal.com/2026/01/05/the-10-best-indian-ads-of-2025/",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2025-03",
        "vertical": "Consumer internet/services",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "Native RO campaign. Product USP communicated through humorous dialogue by servicing professionals. Droll musical score with 1980s Bollywood-style elements. Named among top 10 Indian ads of 2025.",
        "why_included": "Service brand using humor plus product demo hybrid. Retro Bollywood aesthetic is a distinctive pattern interrupt. Relevant: both are home service brands explaining a product benefit clearly.",
        "tags": ["humor", "product-demo", "retro-aesthetic", "professional-talent", "home-service"],
        "deconstructed": False
    },
    {
        "id": "ad_006",
        "advertiser": "HDFC Mutual Fund",
        "platform": "YouTube",
        "format": "In-Feed Video",
        "duration_seconds": 45,
        "language": "Hindi",
        "url": "https://beastoftraal.com/2026/01/05/the-10-best-indian-ads-of-2025/#hdfc",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2025-01",
        "vertical": "Fintech/mutual funds",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "We Are All Investors campaign. Uses Hindi analogies from daily life to explain investment concepts without financial jargon. Emphasizes compounding through relatable everyday scenarios. Top 10 Indian ad of 2025.",
        "why_included": "Takes a complex boring product and makes it relatable through everyday analogies. Wiom faces same challenge: broadband is a commodity. How do you make people care? This ad shows how.",
        "tags": ["analogy", "relatable", "jargon-free", "fintech", "everyday-scenarios", "education"],
        "deconstructed": False
    },
    {
        "id": "ad_007",
        "advertiser": "Cadbury Dairy Milk",
        "platform": "YouTube",
        "format": "TVC",
        "duration_seconds": 60,
        "language": "Hindi",
        "url": "https://beastoftraal.com/2026/01/05/the-10-best-indian-ads-of-2025/#cadbury",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2025-02",
        "vertical": "FMCG",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "New Neighbour campaign. Narrative about inclusivity and language: a woman considers how to retell a story to accommodate a non-local language speaker. Emotional storytelling with a twist. Top 10 Indian ad of 2025.",
        "why_included": "Cadbury is gold standard of Indian emotional advertising. Language and inclusion theme directly relevant to Wiom in multi-lingual India. Masterclass in earned emotional payoff.",
        "tags": ["emotional", "inclusivity", "language", "narrative-twist", "warmth", "FMCG"],
        "deconstructed": False
    },
    {
        "id": "ad_008",
        "advertiser": "Colgate",
        "platform": "YouTube",
        "format": "In-Feed Video",
        "duration_seconds": 30,
        "language": "Hindi",
        "url": "https://www.linkedin.com/posts/karts_advertising-marketing-creative-activity-7211582540191531008-5ATR/",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2024-06",
        "vertical": "FMCG/personal care",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "Night brushing campaign. Playful approach where Colgate sells exciting food items to promote nighttime brushing habits. Inverts expectations: toothpaste brand selling food. Humor drives the message.",
        "why_included": "Inversion pattern: using the unexpected to deliver a boring message. Can Wiom invert expectations? An ISP ad showing life WITHOUT internet to make you appreciate it. Pattern worth studying.",
        "tags": ["inversion", "humor", "unexpected-hook", "behavior-change", "FMCG"],
        "deconstructed": False
    },
    {
        "id": "ad_009",
        "advertiser": "Sony LIV",
        "platform": "YouTube",
        "format": "In-Feed Video",
        "duration_seconds": 45,
        "language": "Hindi",
        "url": "https://beastoftraal.com/2026/01/05/the-10-best-indian-ads-of-2025/#sonyliv",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2025-04",
        "vertical": "OTT/entertainment",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "Shark Tank India S5 registration ad titled Do Not Apply. Satirical reverse-psychology approach discouraging applications to actually drive sign-ups. References employment debates. Top 10 Indian ad of 2025.",
        "why_included": "Reverse psychology as hook. Telling people NOT to do something makes them want to do it. Bold creative choice. Could Wiom say Do Not Switch to test this pattern?",
        "tags": ["reverse-psychology", "satire", "bold-hook", "OTT", "curiosity-gap"],
        "deconstructed": False
    },
    {
        "id": "ad_010",
        "advertiser": "Adani Group",
        "platform": "YouTube",
        "format": "TVC",
        "duration_seconds": 60,
        "language": "Hindi",
        "url": "https://www.linkedin.com/posts/karts_advertising-marketing-creativity-activity-7275722334932480000-JgnP",
        "source": "web_search",
        "date_found": "2026-03-28",
        "date_published": "2024-12",
        "vertical": "Infrastructure/energy",
        "region": "India",
        "tier": None,
        "tier_notes": "",
        "description": "Pehle Pankha Aayega Phir Bijli Aayegi. Mystery narrative with repeated catchphrase creating curiosity. Reveals brand electrification initiative at the end. Named among top 10 Indian ads of 2024.",
        "why_included": "Infrastructure brand making infrastructure interesting through mystery narrative. Directly relevant: broadband is infrastructure too. Curiosity-gap plus catchphrase combo is a retention machine.",
        "tags": ["mystery-narrative", "curiosity-gap", "catchphrase", "infrastructure", "reveal-payoff"],
        "deconstructed": False
    }
]

for ad in ads:
    ok, msg = save_ad(ad)
    print(f"{'OK' if ok else 'FAIL'} | {msg}")
